#!/bin/bash
# Copyright 2022 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

docker run \
  --rm \
  --volume $(pwd):/workspace \
  --workdir /workspace \
  --env NODE_OPTIONS="--experimental-vm-modules --no-warnings" \
  --entrypoint npm \
  node:16.13.1-alpine3.14 \
  $@
