FROM debian:stretch

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz
RUN tar -xzvf hugo_0.55.6_Linux-64bit.tar.gz

ENTRYPOINT ["/hugo"]
