# This Cloud Build file is run automatically when commits land in the website repo.
# See https://console.cloud.google.com/cloud-build/triggers;region=global?project=golang-org.
# Do not run directly.

steps:
  - name: gcr.io/cloud-builders/git
    args: ["clone", "--branch=${_GO_REF}", "--depth=1", "https://go.googlesource.com/go", "_gotmp"]
  - name: gcr.io/cloud-builders/git
    args: ["archive", "--format=zip", "--output=../_goroot.zip", "HEAD"]
    dir: _gotmp
  - name: golang
    args: ["rm", "-rf", "_gotmp"]
  - name: golang
    args: ["go", "test", "./..."]
  - name: golang
    args: ["go", "run", "./cmd/locktrigger", "--project=$PROJECT_ID",
    "--build=$BUILD_ID", "--repo=https://go.googlesource.com/website"]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: ["./go-app-deploy.sh", "cmd/golangorg/app.yaml"]
  - name: golang
    args: ["go", "run", "./cmd/versionprune", "--dry_run=false", "--project=$PROJECT_ID", "--service=default"]

options:
  machineType: N1_HIGHCPU_8
