#!/bin/bash
# Copyright 2024 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This script compares web pages generated by a golangorg web server running locally
# with the pages on the production go.dev server.

go run ./cmd/screentest http://localhost:6060/go.dev https://go.dev ./cmd/golangorg/testdata/screentest/*
