runtime: go116
service: admin
main: ./cmd/admingolangorg

env_variables:
  GOLANGORG_REDIS_ADDR: 10.0.0.4:6379 # instance "gophercache"
  DATASTORE_PROJECT_ID: golang-org
  IAP_AUDIENCE: /projects/397748307997/apps/golang-org

handlers:
  - url: .*
    script: auto
    secure: always

vpc_access_connector:
  name: 'projects/golang-org/locations/us-central1/connectors/golang-vpc-connector'
